{% set name = "seamm-dashboard" %}
{% set version = "2024.1.1" %}
{% set sha256 = "7b204c09274d8e13b49df5276e4b354e5742bef8773e0bcaeaa6c7580ffa7f26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/seamm-dashboard/seamm-dashboard-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  entry_points:
    - seamm_dashboard=seamm_dashboard.results_dashboard:run
    - seamm-dashboard=seamm_dashboard.results_dashboard:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - python >=3.8
    - connexion >=2.7,<3.0
    - email-validator
    - fasteners
    - flask >2.0
    - flask-authorize
    - flask-bootstrap
    - flask-cors
    - flask-jwt-extended >=4.1.0
    - flask-mail
    - flask-marshmallow
    - flask-moment
    - flask-sqlalchemy
    - flask-wtf
    - requests
    - seamm-datastore
    - seamm-util
    - six
    - sqlalchemy <2.0
    - swagger-ui-bundle
    - wtforms
    - flask-compress
    - waitress

test:
  imports:
    - seamm_dashboard
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/molssi-seamm/seamm_dashboard
  summary: A Python package for handling the SEAMM Dashboard database
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/seamm/

extra:
  recipe-maintainers:
    - paulsaxe
